# Generated by Django 4.0.4 on 2022-06-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_images_product_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
