language: python
python:
  - "3.8"
  - "3.9"
  - "3.10.4"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit="*/venv/*,*/migrations/*,*/templatetags/*,manage.py,*/config/*" --source="." manage.py test