language: python
python:
  - "3.6"
  - "3.9"
  - "3.10.4"    
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit="*/venv/*,*/migrations/*,*/templatetags/*,manage.py,*/config/*" --source="." manage.py test